### ISSUE TITLE
 The BEZIER_INSTALL_PREFIX environment variable must be set.

### ISSUE THREAD

**Issue by Hiro420** [jaswon/osu-dreamer#3]
cant install the package as it fails to generate metadata 
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      The BEZIER_INSTALL_PREFIX environment variable must be set.
      [end of output]

**Comment by DaniloPedrazzi** [comment]
The Bezier does not support Python V3.10 or V3.11, Install the version 3.9.10 and you be fine. Here's the link https://www.python.org/ftp/python/3.9.10/
