### ISSUE TITLE
installing python dependencies ... error: metadata-generation-failed

### ISSUE THREAD

**Issue by SmolFry** [jaswon/osu-dreamer#9]
**Describe the bug**
Colab notebook fails to install python dependancies completely.

**To Reproduce**
1. Run the first step of the colab notebook
2. Error occurs

**Expected behavior**
No errors should occur and I should be able to continue to step 2 without issues.

**Screenshots/Files**
![image](https://user-images.githubusercontent.com/98592383/235090474-7d023d9b-f4e5-428d-9df9-118cac4f3bb5.png)

**Comment by jaswon** [comment]
i believe this is fixed, feel free to reopen if not. closing!
